package ar.edu.unq.iu.arena.xtend;

import org.uqbar.arena.bootstrap.CollectionBasedBootstrap;

@SuppressWarnings("all")
public class DominosBootstrap extends CollectionBasedBootstrap {
  public DominosBootstrap() {
    throw new Error("Unresolved compilation problems:"
      + "\nPedido cannot be resolved to a type."
      + "\nCliente cannot be resolved to a type."
      + "\nIngrediente cannot be resolved to a type."
      + "\nPizza cannot be resolved to a type."
      + "\nRepoPedido cannot be resolved."
      + "\nRepoCliente cannot be resolved."
      + "\nRepoIngrediente cannot be resolved."
      + "\nRepoPizza cannot be resolved.");
  }
  
  public void run() {
    throw new Error("Unresolved compilation problems:"
      + "\nPedido cannot be resolved to a type."
      + "\nRepoPedido cannot be resolved to a type."
      + "\nIngrediente cannot be resolved to a type."
      + "\nRepoIngrediente cannot be resolved to a type."
      + "\nCliente cannot be resolved to a type."
      + "\nRepoCliente cannot be resolved to a type."
      + "\nPizza cannot be resolved to a type."
      + "\nRepoPizza cannot be resolved to a type."
      + "\nPizza cannot be resolved."
      + "\nThe method agregarIngrediente(Object) is undefined"
      + "\nThe method agregarIngrediente(Object) is undefined"
      + "\nThe method agregarIngrediente(Object) is undefined"
      + "\nPizza cannot be resolved."
      + "\nThe method agregarIngrediente(Object) is undefined"
      + "\nThe method agregarIngrediente(Object) is undefined"
      + "\nThe method create(Object) is undefined"
      + "\nThe method create(Object) is undefined"
      + "\nPlato cannot be resolved."
      + "\nTamanioPorcion cannot be resolved."
      + "\nThe method or field agregados is undefined"
      + "\nAgregado cannot be resolved."
      + "\nLadoIzquierdo cannot be resolved."
      + "\nPlato cannot be resolved."
      + "\nTamanioFamiliar cannot be resolved."
      + "\nPedido cannot be resolved."
      + "\nDelivery cannot be resolved."
      + "\nThe method or field platos is undefined"
      + "\nThe method or field platos is undefined"
      + "\nPedido cannot be resolved."
      + "\nDelivery cannot be resolved."
      + "\nThe method estado(Object) is undefined"
      + "\nEnViaje cannot be resolved."
      + "\nThe method or field platos is undefined"
      + "\nPedido cannot be resolved."
      + "\nRetirar cannot be resolved."
      + "\nThe method estado(Object) is undefined"
      + "\nCancelado cannot be resolved."
      + "\nThe method or field platos is undefined"
      + "\nPedido cannot be resolved."
      + "\nDelivery cannot be resolved."
      + "\nThe method estado(Object) is undefined"
      + "\nEntregado cannot be resolved."
      + "\nThe method or field platos is undefined"
      + "\nPedido cannot be resolved."
      + "\nRetirar cannot be resolved."
      + "\nThe method or field platos is undefined"
      + "\nThe method create(Object) is undefined"
      + "\nThe method create(Object) is undefined"
      + "\nThe method create(Object) is undefined"
      + "\nThe method create(Object) is undefined"
      + "\nThe method create(Object) is undefined"
      + "\nMenu cannot be resolved."
      + "\nThe method agregarIngredienteExtra(Object) is undefined"
      + "\nThe method agregarIngredienteExtra(Object) is undefined"
      + "\nThe method agregarIngredienteExtra(Object) is undefined"
      + "\nThe method agregarPizza(Object) is undefined"
      + "\nThe method agregarPizza(Object) is undefined"
      + "\ncreate cannot be resolved"
      + "\ncreate cannot be resolved"
      + "\ncreate cannot be resolved"
      + "\ncreate cannot be resolved"
      + "\n=> cannot be resolved"
      + "\n=> cannot be resolved"
      + "\n=> cannot be resolved"
      + "\n=> cannot be resolved"
      + "\nadd cannot be resolved"
      + "\ncreate cannot be resolved"
      + "\ncreate cannot be resolved"
      + "\ncreate cannot be resolved"
      + "\ncreate cannot be resolved"
      + "\ncreate cannot be resolved"
      + "\ndireccion cannot be resolved"
      + "\n=> cannot be resolved"
      + "\nadd cannot be resolved"
      + "\nadd cannot be resolved"
      + "\ndireccion cannot be resolved"
      + "\n=> cannot be resolved"
      + "\nadd cannot be resolved"
      + "\n=> cannot be resolved"
      + "\nadd cannot be resolved"
      + "\ndireccion cannot be resolved"
      + "\n=> cannot be resolved"
      + "\nadd cannot be resolved"
      + "\n=> cannot be resolved"
      + "\nadd cannot be resolved"
      + "\n=> cannot be resolved"
      + "\n=> cannot be resolved");
  }
}
